### ISSUE TITLE
There are active bug reports in rt.cpan.org

### ISSUE THREAD

**Issue by Flimm** [rjbs/Data-UUID#12]
GitHub is the preferred bug tracker for Data::UUID according to its metadata, but there are some open bugs in rt.cpan.org:

https://rt.cpan.org/Public/Dist/Display.html?Status=Active;Name=Data-UUID

rt.cpan.org correctly reminds users to go to GitHub to report issues.

I guess this issue can be closed once those issues are closed or migrated.

**Comment by rjbs** [comment]
all closed or ported
