### ISSUE TITLE
v4 vs v3 UUID on AWSLinux & CentOS

### ISSUE THREAD

**Issue by haisamido** [rjbs/Data-UUID#17]
On AWSLinux (2014.09), this perl module used to generate v4 UUIDs using $ug->to_string( $ug->create()) but something changed in mid-2014 and now it only generates v3's.  http://search.cpan.org/~rjbs/Data-UUID-1.220/UUID.pm used to state that it generates v4 but now it says v3!

On CentOS (6.5) Data::UUID still generates v4 using $ug->to_string( $ug->create()) !!

I'm not sure what's going on here!

**Comment by rjbs** [comment]
This library has never created v4 UUIDs, as far as I know.

Does this help?

https://metacpan.org/changes/distribution/Data-UUID#L53

**Comment by haisamido** [comment]
Interesting!  CentOS 6.5 Data::UUID perl module definitely generates v4.  I know that Data::UUID (at one supplied by AWSLinux) used to generate v4's because I've stored the generated UUIDs and there was a change last year.

**Comment by haisamido** [comment]
I think I know what's going on!  

On CentOS 6.5 Data/UUID.pm is really 'OSSP uuid - Universally Unique Identifier' masquerading as Data::UUID, but on AWSLinux it's what's in https://github.com/rjbs/Data-UUID/ !

**Comment by haisamido** [comment]
"Optional backward compatibility exists for the ISO-C DCE-1.1 and Perl Data::UUID APIs." http://www.ossp.org/pkg/lib/uuid/

**Comment by rjbs** [comment]
Sorry about that — although I can assure you that I'm not at all to blame for it. ;)

I'm marking this closed.  The problem is the distribution, not this code.

**Comment by haisamido** [comment]
Certainly not your problem :-) Sorry about that.
