### ISSUE TITLE
Doesn't compile on Win64 Strawberry Perl

### ISSUE THREAD

**Issue by markwilkinson** [rjbs/Data-UUID#18]
Hi!   This module fails to install on Win64+Strawberry (latest) either via CPAN or via a make/make install from the command line.

See dump below:

PS D:\Strawberry\cpan\build\Data-UUID-1.220-ldsXib> ls

    Directory: D:\Strawberry\cpan\build\Data-UUID-1.220-ldsXib

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        14/04/2015   1:46 PM            smp-test
d----        14/04/2015   1:46 PM            t
-a---        16/12/2014  12:05 AM       4773 Changes
-a---        21/11/2008   9:37 PM       1185 LICENSE
-a---        14/04/2015   1:46 PM      36771 Makefile.old
-a---        07/07/2013   4:56 AM       4704 Makefile.PL
-a---        16/12/2014  12:06 AM        398 MANIFEST
-a---        16/12/2014  12:06 AM       1099 META.json
-a---        16/12/2014  12:06 AM        636 META.yml
-a---        07/07/2013   3:51 AM       5285 ptable.h
-a---        07/07/2013   4:56 AM       1566 README
-a---        18/04/2009   8:07 PM        317 typemap
-a---        16/12/2014  12:01 AM       5244 UUID.h
-a---        16/12/2014  12:05 AM       4327 UUID.pm
-a---        16/12/2014  12:01 AM      15263 UUID.xs

PS D:\Strawberry\cpan\build\Data-UUID-1.220-ldsXib> perl .\Makefile.PL
Checking if your kit is complete...
Looks good
Configured options (run perl Makefile.PL --help for how to change this):
        UUID state storage: C:\Users\ADMINI~1\AppData\Local\Temp
Generating a dmake-style Makefile
Writing Makefile for Data::UUID
Writing MYMETA.yml and MYMETA.json
PS D:\Strawberry\cpan\build\Data-UUID-1.220-ldsXib> dmake
cp UUID.pm blib\lib\Data\UUID.pm
Running Mkbootstrap for Data::UUID ()
"D:\Strawberry\perl\bin\perl.exe" -MExtUtils::Command -e chmod -- 644 "UUID.bs"
"D:\Strawberry\perl\bin\perl.exe" "D:\Strawberry\perl\lib\ExtUtils\xsubpp"  -typemap "D:\STRAWB~1\perl\lib\ExtUtils\type
map" -typemap "typemap"  UUID.xs > UUID.xsc && "D:\Strawberry\perl\bin\perl.exe" -MExtUtils::Command -e mv -- UUID.xsc U
UID.c
gcc -c          -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SY
S -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields -s -O2         -DVERSION=\"1.220\"   -DXS_VERSION=\"1.220\"
"-ID:\STRAWB~1\perl\lib\CORE"  -D_STDIR=\"C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\" -D__MSWin32__ -D_DEFAULT_UMASK=000
7 UUID.c
In file included from D:\STRAWB~1\perl\lib\CORE/hv.h:629:0,
                 from D:\STRAWB~1\perl\lib\CORE/perl.h:3344,
                 from UUID.xs:2:
D:\STRAWB~1\perl\lib\CORE/hv_func.h: In function 'S_perl_hash_murmur3':
D:\STRAWB~1\perl\lib\CORE/hv_func.h:391:17: warning: cast from pointer to integer of different size
In file included from UUID.xs:26:0:
ptable.h: In function 'ptable_find':
ptable.h:107:18: warning: cast from pointer to integer of different size
ptable.h:107:18: warning: cast from pointer to integer of different size
ptable.h:107:18: warning: cast from pointer to integer of different size
ptable.h: In function 'ptable_split':
ptable.h:147:19: warning: cast from pointer to integer of different size
ptable.h:147:19: warning: cast from pointer to integer of different size
ptable.h:147:19: warning: cast from pointer to integer of different size
ptable.h: In function 'ptable_store':
ptable.h:167:20: warning: cast from pointer to integer of different size
ptable.h:167:20: warning: cast from pointer to integer of different size
ptable.h:167:20: warning: cast from pointer to integer of different size
UUID.xs: In function 'inc':
UUID.xs:34:16: warning: cast from pointer to integer of different size
UUID.xs:36:5: warning: cast to pointer from integer of different size
UUID.xs: In function 'XS_Data__UUID_new':
UUID.xs:385:4: warning: cast to pointer from integer of different size
UUID.c: In function 'XS_Data__UUID_create':
UUID.c:573:13: warning: cast to pointer from integer of different size
UUID.c: In function 'XS_Data__UUID_create_from_name':
UUID.c:635:13: warning: cast to pointer from integer of different size
UUID.c: In function 'XS_Data__UUID_compare':
UUID.c:681:13: warning: cast to pointer from integer of different size
UUID.c: In function 'XS_Data__UUID_to_string':
UUID.c:722:13: warning: cast to pointer from integer of different size
UUID.c: In function 'XS_Data__UUID_from_string':
UUID.c:760:13: warning: cast to pointer from integer of different size
UUID.c: In function 'XS_Data__UUID_DESTROY':
UUID.c:859:13: warning: cast to pointer from integer of different size
UUID.xs:581:12: warning: cast from pointer to integer of different size
UUID.xs:583:4: warning: cast to pointer from integer of different size
"D:\Strawberry\perl\bin\perl.exe" -MExtUtils::Mksymlists \
     -e "Mksymlists('NAME'=>\"Data::UUID\", 'DLBASE' => 'UUID', 'DL_FUNCS' => {  }, 'FUNCLIST' => [], 'IMPORTS' => {  },
 'DL_VARS' => []);"
dlltool --def UUID.def --output-exp dll.exp
g++ -o blib\arch\auto\Data\UUID\UUID.xs.dll -Wl,--base-file -Wl,dll.base -mdll -s -L"D:\STRAWB~1\perl\lib\CORE" -L"D:\ST
RAWB~1\c\lib" UUID.o   "D:\STRAWB~1\perl\lib\CORE\libperl520.a" -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomd
lg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lco
mctl32 dll.exp
D:/Strawberry/c/bin/../lib/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of
input file `UUID.o' is incompatible with i386:x86-64 output
D:/Strawberry/c/bin/../lib/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of
input file `dll.exp' is incompatible with i386:x86-64 output
UUID.o:UUID.c:(.text+0x4a): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0x83): undefined reference to `_sprintf'
UUID.o:UUID.c:(.text+0xb8): undefined reference to `_sprintf'
UUID.o:UUID.c:(.text+0xda): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0xed): undefined reference to `__imp__Perl_newSVpv'
UUID.o:UUID.c:(.text+0xfe): undefined reference to `__imp__Perl_sv_2mortal'
UUID.o:UUID.c:(.text+0x25f): undefined reference to `_sprintf'
UUID.o:UUID.c:(.text+0x294): undefined reference to `_sprintf'
UUID.o:UUID.c:(.text+0x2d5): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0x35f): undefined reference to `__imp__Perl_sv_2pv_flags'
UUID.o:UUID.c:(.text+0x39e): undefined reference to `__imp__Perl_sv_derived_from'
UUID.o:UUID.c:(.text+0x3ef): undefined reference to `__imp__Perl_sv_2iv_flags'
UUID.o:UUID.c:(.text+0x40e): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0x44f): undefined reference to `_sscanf'
UUID.o:UUID.c:(.text+0x636): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0x643): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0x654): undefined reference to `__imp__Perl_croak_xs_usage'
UUID.o:UUID.c:(.text+0x666): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0x6eb): undefined reference to `__imp__Perl_sv_2pv_flags'
UUID.o:UUID.c:(.text+0x727): undefined reference to `__imp__Perl_sv_derived_from'
UUID.o:UUID.c:(.text+0x775): undefined reference to `__imp__Perl_sv_2iv_flags'
UUID.o:UUID.c:(.text+0x7e1): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0x7f2): undefined reference to `__imp__Perl_croak_xs_usage'
UUID.o:UUID.c:(.text+0x802): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0x884): undefined reference to `__imp__Perl_sv_2pv_flags'
UUID.o:UUID.c:(.text+0x8d5): undefined reference to `__imp__Perl_sv_2pv_flags'
UUID.o:UUID.c:(.text+0x93c): undefined reference to `__imp__Perl_sv_derived_from'
UUID.o:UUID.c:(.text+0x98d): undefined reference to `__imp__Perl_sv_2iv_flags'
UUID.o:UUID.c:(.text+0xa28): undefined reference to `__imp__Perl_sv_setiv'
UUID.o:UUID.c:(.text+0xa44): undefined reference to `__imp__Perl_mg_set'
UUID.o:UUID.c:(.text+0xa70): undefined reference to `__imp__Perl_sv_newmortal'
UUID.o:UUID.c:(.text+0xaba): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0xace): undefined reference to `__imp__Perl_croak_xs_usage'
UUID.o:UUID.c:(.text+0xadf): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0xaee): undefined reference to `__imp__Perl_push_scope'
UUID.o:UUID.c:(.text+0xb04): undefined reference to `__imp__Perl_save_strlen'
UUID.o:UUID.c:(.text+0xb6d): undefined reference to `__imp__Perl_newSVpv'
UUID.o:UUID.c:(.text+0xb82): undefined reference to `__imp__Perl_sv_2mortal'
UUID.o:UUID.c:(.text+0xba4): undefined reference to `__imp__Perl_call_method'
UUID.o:UUID.c:(.text+0xbc2): undefined reference to `__imp__Perl_newSVsv'
UUID.o:UUID.c:(.text+0xbf3): undefined reference to `__imp__Perl_pop_scope'
UUID.o:UUID.c:(.text+0xc0b): undefined reference to `__imp__Perl_free_tmps'
UUID.o:UUID.c:(.text+0xc33): undefined reference to `__imp__Perl_stack_grow'
UUID.o:UUID.c:(.text+0xc47): undefined reference to `__imp__Perl_markstack_grow'
UUID.o:UUID.c:(.text+0xc59): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0xc71): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0xc80): undefined reference to `__imp__Perl_push_scope'
UUID.o:UUID.c:(.text+0xc96): undefined reference to `__imp__Perl_save_strlen'
UUID.o:UUID.c:(.text+0xd1e): undefined reference to `__imp__Perl_call_method'
UUID.o:UUID.c:(.text+0xd42): undefined reference to `__imp__Perl_free_tmps'
UUID.o:UUID.c:(.text+0xd4d): undefined reference to `__imp__Perl_pop_scope'
UUID.o:UUID.c:(.text+0xd83): undefined reference to `__imp__Perl_stack_grow'
UUID.o:UUID.c:(.text+0xdaf): undefined reference to `__imp__Perl_stack_grow'
UUID.o:UUID.c:(.text+0xdc3): undefined reference to `__imp__Perl_markstack_grow'
UUID.o:UUID.c:(.text+0xddd): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0xdec): undefined reference to `__imp__Perl_push_scope'
UUID.o:UUID.c:(.text+0xe02): undefined reference to `__imp__Perl_save_strlen'
UUID.o:UUID.c:(.text+0xe62): undefined reference to `__imp__Perl_sv_2mortal'
UUID.o:UUID.c:(.text+0xe84): undefined reference to `__imp__Perl_call_method'
UUID.o:UUID.c:(.text+0xec6): undefined reference to `__imp__Perl_sv_2pv_flags'
UUID.o:UUID.c:(.text+0xf0b): undefined reference to `__imp__Perl_pop_scope'
UUID.o:UUID.c:(.text+0xf1f): undefined reference to `__imp__Perl_free_tmps'
UUID.o:UUID.c:(.text+0xf57): undefined reference to `__imp__Perl_stack_grow'
UUID.o:UUID.c:(.text+0xf6b): undefined reference to `__imp__Perl_markstack_grow'
UUID.o:UUID.c:(.text+0xf7d): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0xf8a): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0xf9e): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0x1023): undefined reference to `__imp__Perl_sv_2pv_flags'
UUID.o:UUID.c:(.text+0x106b): undefined reference to `__imp__Perl_sv_derived_from'
UUID.o:UUID.c:(.text+0x10b9): undefined reference to `__imp__Perl_sv_2iv_flags'
UUID.o:UUID.c:(.text+0x114d): undefined reference to `__imp__Perl_newSVpv'
UUID.o:UUID.c:(.text+0x1260): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0x1271): undefined reference to `__imp__Perl_croak_xs_usage'
UUID.o:UUID.c:(.text+0x1288): undefined reference to `_QueryPerformanceCounter@4'
UUID.o:UUID.c:(.text+0x137d): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0x13f4): undefined reference to `__imp__Perl_sv_derived_from'
UUID.o:UUID.c:(.text+0x1445): undefined reference to `__imp__Perl_sv_2iv_flags'
UUID.o:UUID.c:(.text+0x147f): undefined reference to `_rand'
UUID.o:UUID.c:(.text+0x169b): undefined reference to `_srand'
UUID.o:UUID.c:(.text+0x16b7): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0x16c8): undefined reference to `__imp__Perl_croak_xs_usage'
UUID.o:UUID.c:(.text+0x1760): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0x1904): undefined reference to `__imp__PL_memory_wrap'
UUID.o:UUID.c:(.text+0x1915): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0x1926): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0x198f): undefined reference to `__imp__Perl_sv_derived_from'
UUID.o:UUID.c:(.text+0x19da): undefined reference to `__imp__Perl_sv_2iv_flags'
UUID.o:UUID.c:(.text+0x19e8): undefined reference to `_EnterCriticalSection@4'
UUID.o:UUID.c:(.text+0x1a6c): undefined reference to `_LeaveCriticalSection@4'
UUID.o:UUID.c:(.text+0x1b6e): undefined reference to `_LeaveCriticalSection@4'
UUID.o:UUID.c:(.text+0x1b81): undefined reference to `__imp__Perl_croak_nocontext'
UUID.o:UUID.c:(.text+0x1b95): undefined reference to `__imp__Perl_croak_xs_usage'
UUID.o:UUID.c:(.text+0x1bc0): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0x1be7): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0x1c22): undefined reference to `_EnterCriticalSection@4'
UUID.o:UUID.c:(.text+0x1c84): undefined reference to `_LeaveCriticalSection@4'
UUID.o:UUID.c:(.text+0x1cb6): undefined reference to `__imp__Perl_croak_xs_usage'
UUID.o:UUID.c:(.text+0x1cca): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0x1e92): undefined reference to `__errno'
UUID.o:UUID.c:(.text+0x1ea4): undefined reference to `_EnterCriticalSection@4'
UUID.o:UUID.c:(.text+0x1ec7): undefined reference to `_LeaveCriticalSection@4'
UUID.o:UUID.c:(.text+0x1eed): undefined reference to `__imp__Perl_sv_newmortal'
UUID.o:UUID.c:(.text+0x1f24): undefined reference to `__imp__Perl_sv_setref_pv'
UUID.o:UUID.c:(.text+0x1f46): undefined reference to `_GlobalMemoryStatus@4'
UUID.o:UUID.c:(.text+0x1f52): undefined reference to `_GetSystemInfo@4'
UUID.o:UUID.c:(.text+0x1f5e): undefined reference to `_GetSystemTimeAsFileTime@4'
UUID.o:UUID.c:(.text+0x1f6a): undefined reference to `_QueryPerformanceCounter@4'
UUID.o:UUID.c:(.text+0x1f70): undefined reference to `_GetTickCount@0'
UUID.o:UUID.c:(.text+0x1f8c): undefined reference to `_GetComputerNameA@8'
UUID.o:UUID.c:(.text+0x1fb1): undefined reference to `__imp__Perl_newSVpv'
UUID.o:UUID.c:(.text+0x1fc2): undefined reference to `__imp__Perl_sv_2mortal'
UUID.o:UUID.c:(.text+0x2109): undefined reference to `__imp__Perl_croak_xs_usage'
UUID.o:UUID.c:(.text+0x211b): undefined reference to `__imp__Perl_get_context'
UUID.o:UUID.c:(.text+0x2175): undefined reference to `__imp__Perl_xs_apiversion_bootcheck'
UUID.o:UUID.c:(.text+0x2198): undefined reference to `__imp__Perl_xs_version_bootcheck'
UUID.o:UUID.c:(.text+0x21bb): undefined reference to `__imp__Perl_newXS'
UUID.o:UUID.c:(.text+0x24b5): undefined reference to `__imp__Perl_gv_stashpv'
UUID.o:UUID.c:(.text+0x252e): undefined reference to `_InitializeCriticalSection@4'
UUID.o:UUID.c:(.text+0x254a): undefined reference to `__imp__Perl_newSVpv'
UUID.o:UUID.c:(.text+0x256c): undefined reference to `__imp__Perl_newCONSTSUB'
UUID.o:UUID.c:(.text+0x2639): undefined reference to `__imp__Perl_call_list'
collect2.exe: error: ld returned 1 exit status
dmake.exe:  Error code 129, while making 'blib\arch\auto\Data\UUID\UUID.xs.dll'

**Comment by markwilkinson** [comment]
Hmmmm.... it looks like the problem is with the curent Strawberry Perl distribution - it is building 32-bit DLLs instead of 64bit DLLs (as far as I can tell...). 

Anyway, you can close this issue :-)

Cheers!

**Comment by simbabque** [comment]
How did you fix this? I am seeing the same issue with Strawberry 5.24 32bit.

**Comment by leendo** [comment]
Similar responses on Strawberry Perl 5.30.3 and 5.32 64-bit, I am afraid.
